version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-builder
    environment:
      - DOCKER_FE=http://client:5173
      - DOCKER_BE=http://server:3000
    develop:
      watch:
        - action: sync
          path: ./services/src
          target: /src
          # ignore:
          #   - node_modules
        - action: rebuild
          path: ./services/package.json
    ports:
      - 3000:3000
    volumes:
      - pnpm-store:/root/.local/share/pnpm/store
    networks:
      - coorve_network

  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-builder
    environment:
      - VITE_BE_DOCKER=http://server:3000
      - VITE_FE_DOCKER=http://client:5173

    develop:
      watch:
        - action: sync
          path: ./web/src
          target: /src
          # ignore:
          #   - node_modules
        - action: rebuild
          path: .web/package.json
    ports:
      - 5173:5173
    volumes:
      - pnpm-store:/root/.local/share/pnpm/store
    networks:
      - coorve_network

volumes:
  pnpm-store:

networks:
  coorve_network:
