version: "3.8"
services:
  postgress:
    image: postgres:16-alpine
    container_name: coorve_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin

    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
