name: build_services

on:
  push:
    branches:
      - master
    paths:
      - "services/**"
  pull_request:
    branches: ["master"]
    paths:
      - "services/**"

jobs:
  build_services:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node Js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Grab version
        id: version
        run: echo "::setoutput name=version::$(jq -r '.version' services/package.json)"

      - name: Login to Github Container Registry
        # - name: Login to Docker GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN_COORVE }}
          # username: ${{secrets.DOCKERHUB_USERNAME}}
          # password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker build /services --tag ghcr.io/joanbr4/coorve-service-v2:latest
          docker push ghcr.io/joanbr4/coorve-service-v2:latest
        # uses: docker/build-push-action@v3
        # with:
        #   context: services
        #   push: true
        #   tags: bordotch/coorve-service:v${{steps.version.outputs.version}}

      # - name: Update version
      #   run: |
      #     git config --global user.name "Coorve bot"
      #     git config --global user.email "bot@boorve.com"
      #     version=$(grep version: ./config/dev/service.yml)
      #     sed -i "s/version: $version/version: ${{ steps.version.outputs.version }}/" ./config/dev/service.yml
      #     git add ./config/dev/service.yml
      #     git commit -m "Bump service image to v${{ steps.version.outputs.version }}"

      # - name: Create a Pull Request
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     title: "Bump service image version to v${{steps.version.output.version}}"
      #     commit-message: "Bump service image version to v${{ steps.version.outputs.version }}"
      #     branch: "bump-service-to-v${{ steps.version.outputs.version }}"
      #     delete-branch: true
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
      #     assignees: ${{ github.actor }}
  # deploy:
  #   needs: build_services
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: SSH into Server
  #       run: |
  #         sshpass -p ${{secrets. AUTH_PASS}} ssh -o StrictHostKeyChecking=no ${{secrets.AUTH_SERVER}} << EOF
  #           cd /root/bot-vendedor-v2/
  #           docker login ghcr.io -u joanbr4 -p ${{secrets.GH_TOKEN_COORVE}}
  #           docker pull ghcr.io/joanbr4/coorve-service-v2:latest
  #           docker stop coorve_service_v2 && docker rm coorve_service_v2
  #           docker run -d \
  #             --name coorve_service_v2 \
  #             -p 3000:4000 \
  #             # -v $(pwd)/bot_sessions: /app/bot_sessions \
  #             -w/app\ --restart always \ --env-file .env \
  #             ghcr.io/joanbr4/coorve-service-v2:latest
  #         EOF
