name: deploy_services_dev

on:
  push:
    branches: [master]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deply_services_dev:
    if: github.event.push == true
    runs-on: ubuntu-latest

    steps:
      - name: Deploy services
        uses: actions/checkout@v4
