name: deploy_web

on:
  push:
    branches: [master]
    paths:
      - "config/dev/web.yml"

jobs:
  deply_web_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositories
        uses: actions/checkout@v3

      - name: Get versions
        run: |
          echo "service_version=$(grep version: ./config/dev/service.yml | awk '{print $2}')" >> $GITHUB_ENV
          echo "web_version=$(grep version: ./config/dev/web.yml | awk '{print $2}')" >> $GITHUB_ENV

      # - name: Execute SSH Command
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{secrets.SERVER_HOST}}
      #     username: ${{secrets.SERVER_USERNAME}}
      #     key: ${{secrets.SERVER_SSH_KEY}}
      #     script: |
      #       echo "Deploying SERVICE VERSION: ${{ env.service_version }}"
      #       echo "Deploying WEB VERSION: ${{ env.web_version }}"
      #       cd ${{ secrets.SSO_PATH }}/dev
      #       bash deploy.sh front ${{ env.sso_service_version }} ${{ env.usuaris_web_version }}
